name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

#      - name: Login to DockerHub
#        env:
#          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
#          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
#        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
#
#      - name: Build and push service-registry Docker image
#        run: mvn compile jib:build -Dimage=lamvu2010/service-registry:latest
#
#
#      - name: Build and push api-gateway Docker image
#        run: mvn compile jib:build -Dimage=lamvu2010/api-gateway:latest
#
#
#      - name: Build and push identity-service Docker image
#        run: mvn compile jib:build -Dimage=lamvu2010/identity-service:latest
#
#
#      - name: Build and push center-service Docker image
#        run: mvn compile jib:build -Dimage=lamvu2010/center-service:latest
#
#
#      - name: Build and push order-service Docker image
#        run: mvn compile jib:build -Dimage=lamvu2010/order-service:latest
#
#      - name: Deploy with Docker Compose
#        run: docker-compose -f ./docker-compose.yml up -d --build

      - name: Check for OpenSSH client
        run: ssh -V

      - name: Start SSH Agent and Add Key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Test SSH connection
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
        run: |
          ssh -o StrictHostKeyChecking=no ${{SSH_USER}}@${{SSH_HOST}}

      - name: Deploy to Local Machine
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
        run: |
          scp -o StrictHostKeyChecking=no ./scripts.sh ${SSH_USER}@${SSH_HOST}:./scripts.sh
          ssh -o StrictHostKeyChecking=no ${SSH_USER}@${SSH_HOST} 'bash ./scripts.sh'
